name: restart-api
description: "Restart an API container"
inputs:
  apiHost:
    type: string
    required: true
  container:
    type: string
    required: true
  sshKey:
    required: true

runs:
  using: "composite"
  steps:
    - name: Restart API container
      shell: bash
      env:
        SSH_KEY: ${{ inputs.sshKey }}
        API_HOST: ${{ inputs.apiHost }}
        CONTAINER: ${{ inputs.container }}
        MULTI_VAR: ${{ inputs.multiVar }}
      run: |
        echo $MULTI_VAR > multiVar.txt
        cat multiVar.txt

        echo $SSH_KEY | tr -d '\r' > id_rsa
        echo "saving sshkey returned $?"

        chmod 600 id_rsa
        echo "chmod sshkey returned $?"

        echo running : ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i id_rsa ec2-user@$API_HOST "sudo docker restart $CONTAINER"
        ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i id_rsa ec2-user@$API_HOST "sudo docker restart $CONTAINER"
        echo "ssh command returned $?"

        rm -f id_rsa
        echo "rm returned $?"
