name: restart-api
description: "Restart an API container"
inputs:
  apiHost:
    type: string
    required: true
  container:
    type: string
    required: true
  sshKey:
    type: string
    required: true

runs:
  using: "composite"
  steps:
    - name: Restart API container
      shell: bash
      env:
        SSH_KEY: ${{ inputs.sshKey }}
        API_HOST: ${{ inputs.apiHost }}
        CONTAINER: ${{ inputs.container }}
      run: |
        eval $(ssh-agent -s)

        mkdir -p ~/.ssh
        touch ~/.ssh/config
        touch ~/.ssh/known_hosts
        chmod -R 400 ~/.ssh
        echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

        echo "$SSH_KEY" | tr -d '\r' | ssh-add -
        echo "saving sshkey returned $?"

        ssh-keyscan $API_HOST >> ~/.ssh/known_hosts
        echo "ssh-keyscan returned $?"

        echo running : ssh -vvv ec2-user@$API_HOST "sudo docker restart $CONTAINER"
        ssh -vvv ec2-user@$API_HOST "sudo docker restart $CONTAINER"
        echo "ssh command returned $?"
