name: restart-api
description: "Restart an API container"
inputs:
  apiHost:
    type: string
    required: true
  container:
    type: string
    required: true
  sshKey:
    type: string
    required: true
  multiVar:
    type: string
    required: true

runs:
  using: "composite"
  steps:
    - name: Restart API container
      shell: bash
      env:
        SSH_KEY: ${{ inputs.sshKey }}
        API_HOST: ${{ inputs.apiHost }}
        CONTAINER: ${{ inputs.container }}
        MULTI_VAR: ${{ inputs.multiVar }}
      run: |
        echo $MULTI_VAR > multiVar.txt
        cat multiVar.txt

        echo "$SSH_KEY" | tr -d '\r' | ssh-add -
        echo "saving sshkey returned $?"

        ssh-keyscan <ip> >> ~/.ssh/known_hosts
        echo "ssh-keyscan returned $?"

        echo running : ssh -vvv -o StrictHostKeyChecking=no -i id_rsa ec2-user@$API_HOST "sudo docker restart $CONTAINER"
        ssh -vvv -o StrictHostKeyChecking=no -i id_rsa ec2-user@$API_HOST "sudo docker restart $CONTAINER"
        echo "ssh command returned $?"
