name: container-cmd
description: "Execute a container command in start, stop, restart, rm"
inputs:
  apiHost:
    type: string
    required: true
  container:
    type: string
    required: true
  action:
    type: choice
    options:
      - start
      - stop
      - restart
      - rm
    required: true
  sshKey:
    type: string
    required: true

runs:
  using: "composite"
  steps:
    - name: Execute container command
      shell: bash
      env:
        API_HOST: ${{ inputs.apiHost }}
        CONTAINER: ${{ inputs.container }}
        ACTION: ${{ inputs.action }}
        SSH_KEY: ${{ inputs.sshKey }}
      run: |
        eval $(ssh-agent -s)
        echo "$SSH_KEY" | tr -d '\r' | ssh-add -
        SSH_CONFIG="-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"

        ssh $SSH_CONFIG ec2-user@$API_HOST "echo Executing $ACTION on $CONTAINER && sudo docker $ACTION $CONTAINER"
