name: container-cmd
description: "Execute a container command in start, stop, restart, rm"
inputs:
  apiHost:
    type: string
    required: true
  container:
    type: string
    required: true
  action:
    type: choice
    options:
      - start
      - stop
      - restart
      - rm
    required: true
  sshKey:
    type: string
    required: true

runs:
  using: "composite"
  steps:
    - name: Execute container stop
      if: inputs.action == 'stop'
      shell: bash
      env:
        SSH_KEY: ${{ inputs.sshKey }}
        API_HOST: ${{ inputs.apiHost }}
        CONTAINER: ${{ inputs.container }}
        ACTION: ${{ inputs.action }}
      run: |
        eval $(ssh-agent -s)
        echo "$SSH_KEY" | tr -d '\r' | ssh-add -
        SSH_CONFIG="-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"

        ssh $SSH_CONFIG ec2-user@$API_HOST "echo Executing $ACTION on $CONTAINER && [ -z (sudo docker ps -q -f name=${CONTAINER}) ] && echo 'Container already stopped' || sudo docker stop $CONTAINER"

    - name: Execute container start
      if: inputs.action == 'start'
      shell: bash
      env:
        SSH_KEY: ${{ inputs.sshKey }}
        API_HOST: ${{ inputs.apiHost }}
        CONTAINER: ${{ inputs.container }}
        ACTION: ${{ inputs.action }}
      run: |
        eval $(ssh-agent -s)
        echo "$SSH_KEY" | tr -d '\r' | ssh-add -
        SSH_CONFIG="-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"

        ssh $SSH_CONFIG ec2-user@$API_HOST "echo Executing $ACTION on $CONTAINER && [ -z (sudo docker ps -q -f name=${CONTAINER}) ] && sudo docker start $CONTAINER || echo 'Container already started'"

    - name: Execute container command
      if: inputs.action == 'rm'
      shell: bash
      env:
        SSH_KEY: ${{ inputs.sshKey }}
        API_HOST: ${{ inputs.apiHost }}
        CONTAINER: ${{ inputs.container }}
        ACTION: ${{ inputs.action }}
      run: |
        eval $(ssh-agent -s)
        echo "$SSH_KEY" | tr -d '\r' | ssh-add -
        SSH_CONFIG="-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"

        ssh $SSH_CONFIG ec2-user@$API_HOST "echo Executing $ACTION on $CONTAINER && sudo docker rm -f $CONTAINER"

    - name: Execute container command
      if: inputs.action == 'restart'
      shell: bash
      env:
        SSH_KEY: ${{ inputs.sshKey }}
        API_HOST: ${{ inputs.apiHost }}
        CONTAINER: ${{ inputs.container }}
        ACTION: ${{ inputs.action }}
      run: |
        eval $(ssh-agent -s)
        echo "$SSH_KEY" | tr -d '\r' | ssh-add -
        SSH_CONFIG="-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"

        ssh $SSH_CONFIG ec2-user@$API_HOST "echo Executing $ACTION on $CONTAINER && sudo docker $ACTION $CONTAINER"
