name: stop-container
description: "Stop a container"
inputs:
  apiHost:
    type: string
    required: true
  container:
    type: string
    required: true
  action:
    type: choice
    options:
      - start
      - stop
      - restart
    required: true

runs:
  using: "composite"
  steps:
    - name: Stop container
      shell: bash
      env:
        API_HOST: ${{ inputs.apiHost }}
        CONTAINER: ${{ inputs.container }}
        ACTION: ${{ inputs.action }}
      run: |
        SSH_CONFIG="-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"

        ssh $SSH_CONFIG ec2-user@$API_HOST "echo Executing $ACTION on $CONTAINER && sudo docker $ACTION $CONTAINER"
