version: "3"
services:
  api:
    image: 940219468121.dkr.ecr.eu-west-3.amazonaws.com/yz:${TAG}
    ports:
      - "80:80"
    environment:
      - JSON_RPC_URL
      - DIRECTORY_ADDRESS
      - MONGODB_HOST=localhost
      - BIND_ADDRESS=0.0.0.0
    healthcheck:
      test: curl -f http://localhost/health
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: awslogs
      options:
        awslogs-group: yz-api
        awslogs-region: eu-west-3
        awslogs-stream-prefix: 'yz-api'
  db:
    image: mongo:6.0
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: awslogs
      options:
        awslogs-group: yz-db
        awslogs-region: eu-west-3
        awslogs-stream-prefix: 'yz-db'
