version: "3.3"
services:
  api:
    build: .
    image: ct-api
    ports:
      - "4000:4000"
    environment:
      - JSON_RPC_URL=https://matic-mumbai.chainstacklabs.com
      - DIRECTORY_ADDRESS=0xA94F250f2508A9be616e0922742Bb0628474F906
      - MONGODB_HOST=db

  db:
    image: mongo:6.0
