version: "3"
services:
  api:
    image: 940219468121.dkr.ecr.eu-west-3.amazonaws.com/yz:${TAG}
    ports:
      - "80:80"
    environment:
      - MONGODB_HOST=localhost
      - BIND_ADDRESS=0.0.0.0
      - BIND_PORT=80
      - CORS_ORIGINS=https://test.yz-network.com
    healthcheck:
      test: curl -f http://localhost/health
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: awslogs
      options:
        awslogs-group: yz-api
        awslogs-region: eu-west-3
        awslogs-stream-prefix: "yz-api"
  dbsetup:
    image: mongo:6.0
    entrypoint:
      [
        "bash",
        "-c",
        "sleep 10 && mongosh --host db:27017 --eval 'rs.initiate()'",
      ]
    logging:
      driver: awslogs
      options:
        awslogs-group: yz-db-setup
        awslogs-region: eu-west-3
        awslogs-stream-prefix: "yz-db-setup"
  db:
    image: mongo:6.0
    entrypoint: ["/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0"]
    ports:
      - "27017:27017"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: awslogs
      options:
        awslogs-group: yz-db
        awslogs-region: eu-west-3
        awslogs-stream-prefix: "yz-db"
