name: setup-ssh
description: "Starts SSH agent and import private key"
inputs:
  sshKey:
    type: string
    required: true

runs:
  using: "composite"
  steps:
    - name: Configure SSH Agent
      shell: bash
      env:
        SSH_KEY: ${{ inputs.sshKey }}
      run: |
        eval $(ssh-agent -s)
        echo "$SSH_KEY" | tr -d '\r' | ssh-add -
