name: deploy-api
description: "Starts or update an API container"
inputs:
  apiHost:
    type: string
    required: true
  container:
    type: string
    required: true
  logGroup:
    type: string
    required: true
  imageTag:
    type: choice
    options:
      - snapshot
      - release
    required: true
  configVar:
    type: string
    required: true
  sshKey:
    type: string
    required: true

runs:
  using: "composite"
  steps:
    - name: Deploy API container
      shell: bash
      env:
        API_HOST: ${{ inputs.apiHost }}
        CONTAINER: ${{ inputs.container }}
        LOG_GROUP: ${{ inputs.logGroup }}
        IMAGE_TAG: ${{ inputs.imageTag }}
        CONFIG_VAR: ${{ inputs.configVar }}
        SSH_KEY: ${{ inputs.sshKey }}
      run: |
        eval $(ssh-agent -s)
        echo "$SSH_KEY" | tr -d '\r' | ssh-add -
        SSH_CONFIG="-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"

        cat <<EOF | ssh $SSH_CONFIG ec2-user@$API_HOST
          echo "Authenticating to ECR"
          sudo docker login --username AWS -p $(aws ecr get-login-password --region eu-west-3) 940219468121.dkr.ecr.eu-west-3.amazonaws.com

          echo "Pulling ${IMAGE_TAG} image"
          sudo docker pull 940219468121.dkr.ecr.eu-west-3.amazonaws.com/yz-image:${IMAGE_TAG}

          echo "Loading configuration from SSM"
          CONFIG=$(aws ssm get-parameter --name $CONFIG_VAR --query "Parameter.Value" --output text)

          echo "Starting container"
          sudo docker run --log-driver=awslogs --log-opt awslogs-create-group=true --log-opt awslogs-group=${LOG_GROUP} \
            -d --name $CONTAINER --restart always --network db_net -e "CONFIG=$CONFIG" \
            --health-cmd "curl -f http://localhost/health" \
            --health-interval 30s --health-timeout 10s --health-retries 5 \
            940219468121.dkr.ecr.eu-west-3.amazonaws.com/yz-image:${IMAGE_TAG}
          sudo docker network connect api_net $CONTAINER

          echo "Done"
        EOF
