name: deploy-api
description: "Starts or update an API container"
inputs:
  apiHost:
    type: string
    required: true
  container:
    type: string
    required: true
  logGroup:
    type: string
    required: true
  imageTag:
    type: choice
    options:
      - snapshot
      - release
    required: true
  configVar:
    type: string
    required: true
  sshKey:
    type: string
    required: true

runs:
  using: "composite"
  steps:
    - name: Deploy API container
      shell: bash
      env:
        API_HOST: ${{ inputs.apiHost }}
        CONTAINER: ${{ inputs.container }}
        LOG_GROUP: ${{ inputs.logGroup }}
        IMAGE_TAG: ${{ inputs.imageTag }}
        CONFIG_VAR: ${{ inputs.configVar }}
        SSH_KEY: ${{ inputs.sshKey }}
      run: |
        eval $(ssh-agent -s)
        echo "$SSH_KEY" | tr -d '\r' | ssh-add -
        SSH_CONFIG="-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"

        scp .github/actions/deploy-api/deploy.sh ec2-user@$API_HOST:/tmp
        ssh ec2-user@$API_HOST "IMAGE_TAG=$IMAGE_TAG CONFIG_VAR=$CONFIG_VAR CONTAINER=$CONTAINER LOG_GROUP=$LOG_GROUP /bin/bash /tmp/deploy.sh"
