name: Reset Database

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Which environment to reset"
        type: choice
        options:
          - testing
          - production
          - both
        required: true
        default: "testing"

concurrency: ${{ github.ref }}

jobs:
  reset-testing:
    if: inputs.environment == 'testing' || inputs.environment == 'both'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: ./.github/actions/setup-ssh
        with:
          sshKey: ${{ secrets.SSH_KEY }}

      - name: Stop container
        uses: ./.github/actions/container-cmd
        with:
          apiHost: ${{ vars.API_HOST }}
          container: ${{ vars.TEST_API_CONTAINER }}
          action: stop

      - name: Clear DB
        uses: ./.github/actions/reset-db
        with:
          apiHost: ${{ vars.API_HOST }}
          dbContainer: ${{ vars.DB_CONTAINER }}
          database: ${{ vars.TEST_DB_NAME }}

      - name: Start container
        uses: ./.github/actions/container-cmd
        with:
          apiHost: ${{ vars.API_HOST }}
          container: ${{ vars.TEST_API_CONTAINER }}
          action: start

  reset-production:
    if: inputs.environment == 'production' || inputs.environment == 'both'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: ./.github/actions/setup-ssh
        with:
          sshKey: ${{ secrets.SSH_KEY }}

      - name: Stop container
        uses: ./.github/actions/container-cmd
        with:
          apiHost: ${{ vars.API_HOST }}
          container: ${{ vars.PROD_API_CONTAINER }}
          action: stop

      - name: Clear DB
        uses: ./.github/actions/reset-db
        with:
          apiHost: ${{ vars.API_HOST }}
          dbContainer: ${{ vars.DB_CONTAINER }}
          database: ${{ vars.PROD_DB_NAME }}
          sshKey: ${{ secrets.SSH_KEY }}

      - name: Start container
        uses: ./.github/actions/container-cmd
        with:
          apiHost: ${{ vars.API_HOST }}
          container: ${{ vars.PROD_API_CONTAINER }}
          action: start
