name: Restart API

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Which environment to restart"
        type: choice
        options:
          - testing
          - production
          - both
        required: true
        default: "testing"

concurrency: ${{ github.ref }}

jobs:
  restart-testing:
    if: inputs.environment == 'testing' || inputs.environment == 'both'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: ./.github/actions/setup-ssh
        with:
          sshKey: ${{ secrets.SSH_KEY }}

      - name: Restart
        uses: ./.github/actions/container-cmd
        with:
          apiHost: ${{ vars.API_HOST }}
          container: ${{ vars.TEST_API_CONTAINER }}
          action: restart

  restart-production:
    if: inputs.environment == 'production' || inputs.environment == 'both'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: ./.github/actions/setup-ssh
        with:
          sshKey: ${{ secrets.SSH_KEY }}

      - name: Restart
        uses: ./.github/actions/container-cmd
        with:
          apiHost: ${{ vars.API_HOST }}
          container: ${{ vars.TEST_API_CONTAINER }}
          action: restart
