name: Restart API

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Which environment to restart"
        type: choice
        options:
          - testing
          - production
          - both
        required: true
        default: "testing"

concurrency: ${{ github.ref }}

jobs:
  restart-testing:
    if: inputs.environment == 'testing' || inputs.environment == 'both'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Restart
        uses: ./.github/actions/restart-api
        with:
          apiHost: ${{ env.API_HOST }}
          container: ${{ env.TEST_API_CONTAINER }}
        secrets:
          sshKey: ${{ secrets.SSH_KEY }}

  restart-production:
    if: inputs.environment == 'production' || inputs.environment == 'both'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Restart
        uses: ./.github/actions/restart-api
        with:
          apiHost: ${{ env.API_HOST }}
          container: ${{ env.PROD_API_CONTAINER }}
        secrets:
          sshKey: ${{ secrets.SSH_KEY }}
